const fs=require('fs');
const extra=
const Link={create:d=>{const l=require("./db").links.read();d._id="l_"+Date.now();d.created_at=new Date().toISOString();d.total_clicks=d.total_clicks||0;l.push(d);require("./db").links.write(l);return d},find:f=>{let l=require("./db").links.read();if(f&&f.category)l=l.filter(x=>x.category===f.category);return l.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))},findOne:f=>{const l=require("./db").links.read();return l.find(x=>Object.keys(f).every(k=>x[k]===f[k]))||null},findById:id=>require("./db").links.read().find(x=>x._id===id)||null,findByIdAndUpdate:(id,up)=>{const l=require("./db").links.read();const i=l.findIndex(x=>x._id===id);if(i===-1)return null;l[i]={...l[i],...up};require("./db").links.write(l);return l[i]},findByIdAndDelete:id=>{let l=require("./db").links.read();const i=l.findIndex(x=>x._id===id);if(i===-1)return null;l.splice(i,1);require("./db").links.write(l);return!0},distinct:field=>{const l=require("./db").links.read();return[...new Set(l.map(x=>x[field]))]}};
const Session={create:d=>{const s=require("./db").sessions.read();d._id="s_"+Date.now();d.timestamp=new Date().toISOString();d.isLive=!0;s.push(d);require("./db").sessions.write(s);return d},find:()=>require("./db").sessions.read().sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)),findById:id=>require("./db").sessions.read().find(x=>x._id===id)||null,findByIdAndUpdate:(id,up)=>{const s=require("./db").sessions.read();const i=s.findIndex(x=>x._id===id);if(i===-1)return null;s[i]={...s[i],...up};require("./db").sessions.write(s);return s[i]},findByIdAndDelete:id=>{let s=require("./db").sessions.read();const i=s.findIndex(x=>x._id===id);if(i===-1)return null;s.splice(i,1);require("./db").sessions.write(s);return!0},countDocuments:f=>{let s=require("./db").sessions.read();if(f&&f.deviceType)s=s.filter(x=>x.deviceType===f.deviceType);return s.length}};
const Trash={create:d=>{const t=require("./db").trash.read();d._id="t_"+Date.now();d.deletedAt=new Date().toISOString();t.push(d);require("./db").trash.write(t);return d},find:()=>require("./db").trash.read().sort((a,b)=>new Date(b.deletedAt)-new Date(a.deletedAt)),findById:id=>require("./db").trash.read().find(x=>x._id===id)||null,findByIdAndDelete:id=>{let t=require("./db").trash.read();const i=t.findIndex(x=>x._id===id);if(i===-1)return null;t.splice(i,1);require("./db").trash.write(t);return!0},deleteMany:()=>require("./db").trash.write([]),countDocuments:()=>require("./db").trash.read().length};
const MenuItem={create:d=>{const m=require("./db").menuItems.read();d._id="m_"+Date.now();d.created_at=new Date().toISOString();m.push(d);require("./db").menuItems.write(m);return d},find:()=>require("./db").menuItems.read().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)),findByIdAndUpdate:(id,up)=>{const m=require("./db").menuItems.read();const i=m.findIndex(x=>x._id===id);if(i===-1)return null;m[i]={...m[i],...up};require("./db").menuItems.write(m);return m[i]},findByIdAndDelete:id=>{let m=require("./db").menuItems.read();const i=m.findIndex(x=>x._id===id);if(i===-1)return null;m.splice(i,1);require("./db").menuItems.write(m);return!0}};
const RouteLog={create:d=>{const l=require("./db").routeLogs.read();d._id="r_"+Date.now();d.changedAt=new Date().toISOString();l.push(d);require("./db").routeLogs.write(l);return d}};
const Click={create:d=>{const c=require("./db").clicks.read();d._id="c_"+Date.now();d.clickedAt=new Date().toISOString();c.push(d);require("./db").clicks.write(c);return d}};
;
const existing=fs.readFileSync("models.js","utf8");
const updated=extra+"\n"+existing;
const final=updated.replace("module.exports={User}","module.exports={User,Link,Session,Trash,MenuItem,RouteLog,Click}");
fs.writeFileSync("models.js",final);
console.log("Models built successfully!");
